export type KucoinBotTemplate = {
  id: string;
  name: string;
  kucoinEquivalent: string;
  market: "spot" | "futures" | "portfolio";
  automationMode: "ai" | "semi-auto";
  coreLogic: string;
  keyInputs: string[];
  marketFit: string;
  feeSensitivity: "low" | "medium" | "high";
  testingPriority: "phase-1" | "phase-2" | "phase-3";
};

export const kucoinBotCatalog: KucoinBotTemplate[] = [
  {
    id: "spot-grid",
    name: "Spot Grid",
    kucoinEquivalent: "Spot Grid",
    market: "spot",
    automationMode: "semi-auto",
    coreLogic: "Places layered buy and sell orders inside a fixed range to harvest sideways volatility.",
    keyInputs: ["price range", "grid count", "investment amount"],
    marketFit: "Best in range-bound spot markets with repeated oscillation.",
    feeSensitivity: "high",
    testingPriority: "phase-1",
  },
  {
    id: "futures-grid",
    name: "Futures Grid",
    kucoinEquivalent: "Futures Grid",
    market: "futures",
    automationMode: "semi-auto",
    coreLogic: "Runs a leveraged grid with long or short bias, usually with AI-generated or custom range settings.",
    keyInputs: ["direction", "price range", "grid count", "leverage", "margin"],
    marketFit: "Best in volatile but bounded futures markets.",
    feeSensitivity: "high",
    testingPriority: "phase-1",
  },
  {
    id: "infinity-grid",
    name: "Infinity Grid",
    kucoinEquivalent: "Infinity Grid",
    market: "spot",
    automationMode: "semi-auto",
    coreLogic: "Extends grid logic upward in trend conditions instead of forcing a hard top boundary.",
    keyInputs: ["lower bound", "profit per grid", "investment amount"],
    marketFit: "Best in sustained uptrends where classic grids cap upside too early.",
    feeSensitivity: "medium",
    testingPriority: "phase-2",
  },
  {
    id: "smart-rebalance",
    name: "Smart Rebalance",
    kucoinEquivalent: "Smart Rebalance",
    market: "portfolio",
    automationMode: "ai",
    coreLogic: "Maintains target portfolio weights using threshold or periodic rebalance rules.",
    keyInputs: ["asset weights", "rebalance trigger", "entry prices", "stop loss", "take profit"],
    marketFit: "Best for long-term diversified portfolios instead of single-pair trading.",
    feeSensitivity: "medium",
    testingPriority: "phase-1",
  },
  {
    id: "dca",
    name: "DCA Bot",
    kucoinEquivalent: "DCA",
    market: "spot",
    automationMode: "semi-auto",
    coreLogic: "Buys on a schedule with optional profit target behavior to smooth entry timing.",
    keyInputs: ["investment interval", "order amount", "max investment", "profit target"],
    marketFit: "Best for accumulation, not short-term trading alpha.",
    feeSensitivity: "low",
    testingPriority: "phase-1",
  },
  {
    id: "grid-martingale-spot",
    name: "Spot Martingale",
    kucoinEquivalent: "Grid Spot Martingale",
    market: "spot",
    automationMode: "semi-auto",
    coreLogic: "Adds size as price drops to lower the average cost, then exits the whole basket on rebound.",
    keyInputs: ["safety order size", "step ratio", "take profit", "max rounds"],
    marketFit: "Works only with strict risk caps and non-collapse conditions.",
    feeSensitivity: "high",
    testingPriority: "phase-2",
  },
  {
    id: "margin-grid",
    name: "Margin Grid",
    kucoinEquivalent: "Margin Grid",
    market: "spot",
    automationMode: "semi-auto",
    coreLogic: "Runs a spot-style grid with borrowed capital to amplify returns and risk.",
    keyInputs: ["range", "grid count", "borrow amount", "interest cost"],
    marketFit: "Only useful after borrow costs and liquidation behavior are fully modeled.",
    feeSensitivity: "high",
    testingPriority: "phase-3",
  },
  {
    id: "ai-spot-trend",
    name: "AI Spot Trend",
    kucoinEquivalent: "AI Spot Trend",
    market: "spot",
    automationMode: "ai",
    coreLogic: "Tracks bullish spot trends using stochastic indicators plus weighted moving averages on 1-hour cycles.",
    keyInputs: ["pair", "investment amount", "trend confirmation window"],
    marketFit: "Best near the beginning of a bullish trend.",
    feeSensitivity: "medium",
    testingPriority: "phase-1",
  },
  {
    id: "ai-dynamic",
    name: "AI Dynamic",
    kucoinEquivalent: "AI Dynamic",
    market: "spot",
    automationMode: "ai",
    coreLogic: "AI-managed allocation and parameter adjustment bot referenced by KuCoin’s fee rules for spot bots.",
    keyInputs: ["pair basket", "AI allocation", "rebalance logic"],
    marketFit: "Likely best after we have richer allocation and adaptive parameter infrastructure.",
    feeSensitivity: "medium",
    testingPriority: "phase-3",
  },
  {
    id: "ai-futures-trend",
    name: "AI Futures Trend",
    kucoinEquivalent: "AI Futures Trend",
    market: "futures",
    automationMode: "ai",
    coreLogic: "Trend-following futures bot that should combine direction, leverage, and risk controls under AI-selected settings.",
    keyInputs: ["pair", "direction", "leverage", "margin"],
    marketFit: "Best in sustained futures trends with robust risk constraints.",
    feeSensitivity: "medium",
    testingPriority: "phase-2",
  },
  {
    id: "futures-martingale",
    name: "Futures Martingale",
    kucoinEquivalent: "Futures Martingale",
    market: "futures",
    automationMode: "semi-auto",
    coreLogic: "Averages into futures positions as price moves against the initial entry, then exits on recovery.",
    keyInputs: ["leverage", "safety order ladder", "take profit", "stop loss"],
    marketFit: "Very capital and liquidation sensitive, especially for small balances.",
    feeSensitivity: "high",
    testingPriority: "phase-3",
  },
  {
    id: "dualfutures-ai",
    name: "DualFutures AI",
    kucoinEquivalent: "DualFutures AI",
    market: "futures",
    automationMode: "ai",
    coreLogic: "AI-driven futures strategy with conservative and aggressive modes, directional adaptation, and built-in risk management.",
    keyInputs: ["aggressive or conservative mode", "pair", "margin", "risk controls"],
    marketFit: "Best after a mature futures execution and portfolio risk engine exists.",
    feeSensitivity: "medium",
    testingPriority: "phase-3",
  },
];
